/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import LogicaJuego.ListaMiniaturas;
import LogicaJuego.ListaEscenografia;

/**
 *
 * @author Ignacio
 */
public class Tablero extends javax.swing.JPanel
{

    private final PantallaJuego Padre;
    private final int anchoTotal = 2000;    //6 metros
    private final int altoTotal = 1000;     //6 metros
    private int zoom;
    private int esquinaAncho;
    private int esquinaAlto;
    private boolean click;
    private int lastX;
    private int lastY;
    private int lastclick;

    private ListaMiniaturas Lt;
    private ListaEscenografia Et;

    /**
     * Creates new form Tablero
     */
    public Tablero(PantallaJuego padre)
    {
        Padre = padre;
        initComponents();
        zoom = 100;
        esquinaAncho = 0;
        esquinaAlto = 0;
        lastX = 0;
        lastY = 0;
    }

    public void refresh(ListaMiniaturas L, ListaEscenografia E)
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBackground(new java.awt.Color(255, 255, 204));
        addMouseWheelListener(new java.awt.event.MouseWheelListener()
        {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt)
            {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt)//GEN-FIRST:event_formMouseWheelMoved
    {//GEN-HEADEREND:event_formMouseWheelMoved
        zoom += evt.getWheelRotation() * 10;
        if (zoom < 10) {
            zoom = 10;
        }
        if (zoom > 100) {
            zoom = 100;
        }
        refresh(Lt, Et);
    }//GEN-LAST:event_formMouseWheelMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
        int X = evt.getX();
        int Y = evt.getY();
        if (!click) {
            if (/*ficha*/false) {
                lastclick =2;
                
            } else {
                lastclick = 1;

            }
            
        } else {
            if (/*ficha*/false) {

            } else {
                if(lastclick==1 && ((X-lastX)>5 || (Y-lastY)>5))
                {
                    lastclick=0;
                    esquinaAncho=(X+lastX)/zoom;
                    esquinaAlto=(Y+lastY)/zoom;
                    esquinaAncho=Math.min(Math.max(0, X),anchoTotal-(anchoTotal*zoom/100));
                    esquinaAlto=Math.min(Math.max(0, Y),altoTotal-(altoTotal*zoom/100));
                    System.out.println("Movido en " + (lastX-esquinaAncho) + " " + (lastY-esquinaAlto));
                }
                else if(lastclick==1)
                {
                    Padre.abrirmenu(lastX,lastY); 
                    lastclick=0;
                    System.out.println("Abrir menu en " + X + " " + Y);
                } if(lastclick==2){}
                

            }

        }
        click=!click;
        lastX = X;
        lastY = Y;
        refresh(Lt,Et);
        System.out.println("Click en " + X + " " + Y);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
