/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2017-12-19 14:11:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h1>Reparto de regalos</h1>\n");
      out.write("        ");

            //FORMULARIO QUE PIDE 4 REGALOS: X Y (0-500) PESO (1 a 5)
            //Seleccionar persona que entrega
            //En caso de error va a página de error
        
      out.write("\n");
      out.write("        <form action=\"Grafico.jsp\" method=\"post\">\n");
      out.write("            <table>\n");
      out.write("                <tr><td></td><td>Coord X</td><td>Coord Y</td><td>Peso Regalo</td>\n");
      out.write("                <tr><td>Regalo 1</td>\n");
      out.write("                    <td><input type=\"number\" min=\"0\" max=\"500\" value=\"0\" name=\"x1\"></td>\n");
      out.write("                    <td><input type=\"number\" min=\"0\" max=\"500\" value=\"0\" name=\"y1\"></td>\n");
      out.write("                    <td><input type=\"number\" min=\"1\" max=\"5\" value=\"1\" name=\"p1\"></td></tr> \n");
      out.write("                <tr><td>Regalo 2</td>\n");
      out.write("                    <td><input type=\"number\" min=\"0\" max=\"500\" value=\"0\" name=\"x2\"></td>\n");
      out.write("                    <td><input type=\"number\" min=\"0\" max=\"500\" value=\"0\" name=\"y2\"></td>\n");
      out.write("                    <td><input type=\"number\" min=\"1\" max=\"5\" value=\"1\" name=\"p2\"></td></tr> \n");
      out.write("                <tr><td>Regalo 3</td>\n");
      out.write("                    <td><input type=\"number\" min=\"0\" max=\"500\" value=\"0\" name=\"x3\"></td>\n");
      out.write("                    <td><input type=\"number\" min=\"0\" max=\"500\" value=\"0\" name=\"y3\"></td>\n");
      out.write("                    <td><input type=\"number\" min=\"1\" max=\"5\" value=\"1\" name=\"p3\"></td></tr> \n");
      out.write("                <tr><td>Regalo 4</td>\n");
      out.write("                    <td><input type=\"number\" min=\"0\" max=\"500\" value=\"0\" name=\"x4\"></td>\n");
      out.write("                    <td><input type=\"number\" min=\"0\" max=\"500\" value=\"0\" name=\"y4\"></td>\n");
      out.write("                    <td><input type=\"number\" min=\"1\" max=\"5\" value=\"1\" name=\"p4\"></td></tr> \n");
      out.write("                <tr><td>Repartidor</td><td colspan= \"3\">\n");
      out.write("                        <select name=\"persona\">\n");
      out.write("                            <option value=\"noel\">Papa Noel</option>\n");
      out.write("                            <option value=\"melchor\">Melchor</option>\n");
      out.write("                            <option value=\"gaspar\">Gaspar</option>\n");
      out.write("                            <option value=\"baltasar\">Baltasar</option>\n");
      out.write("                        </select>    \n");
      out.write("                    </td></tr> \n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td align=\"right\" colspan= \"2\"><input type=\"reset\" name=\"vaciar\" value=\"Reset\"/></td>\n");
      out.write("                    <td colspan= \"2\"><input type=\"submit\" name=\"submit\" value=\"Calcular\"/></td>\n");
      out.write("                </tr>    \n");
      out.write("            </table>\n");
      out.write("        </form> \n");
      out.write("    </table>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
